priority_rules:
  - name: OCI workflow updates
    priority: 3000
    conditions:
      - label=update
      - label=digests
  - name: Renovate digest updates
    priority: 2500
    conditions:
      - author~=^renovate
      - label=digest-update
  - name: Renovate tag updates
    priority: 2000
    conditions:
      - author~=^renovate
      - label=tag-update

queue_rules:
  - name: default
    merge_method: rebase

pull_request_rules:
  - name: Auto-merge OCI workflow updates
    conditions:
      - label=update
      - label=digests
      - "#approved-reviews-by>=0"  # No approval required for automated updates
    actions:
      queue:
        name: default

  - name: Auto-merge Renovate digest updates
    conditions:
      - author~=^renovate
      - label=dependencies
      - label=docker
      - label=digest-update
    actions:
      queue:
        name: default

  - name: Auto-merge Renovate tag updates
    conditions:
      - author~=^renovate
      - label=dependencies
      - label=docker
      - label=tag-update
    actions:
      queue:
        name: default
