priority_rules:
  - name: Renovate tag updates
    priority: 3000
    conditions:
      - author~=^renovate
      - label=tag-update
  - name: Renovate digest updates
    priority: 2500
    conditions:
      - author~=^renovate
      - label=digest-update
  - name: OCI workflow updates
    priority: 2000
    conditions:
      - label=update
      - label=digests
  - name: GitHub Actions updates
    priority: 1000
    conditions:
      - author~=^renovate
      - label=github-actions
  - name: Nix flake updates
    priority: 500
    conditions:
      - author~=^renovate
      - label=nix-flake

queue_rules:
  - name: default
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})
      {% if body %}

      {{ body }}
      {% endif %}
  
  - name: rebase-queue
    merge_method: rebase

pull_request_rules:
  - name: Auto-merge OCI workflow updates
    conditions:
      - label=update
      - label=digests
      - "#approved-reviews-by>=0"  # No approval required for automated updates
    actions:
      queue:
        name: rebase-queue  # Keep multiple commits for transparency

  - name: Auto-merge Renovate digest updates
    conditions:
      - author~=^renovate
      - label=dependencies
      - label=docker
      - label=digest-update
    actions:
      queue:
        name: default  # Squash - many small digest updates

  - name: Auto-merge Renovate tag updates
    conditions:
      - author~=^renovate
      - label=dependencies
      - label=docker
      - label=tag-update
    actions:
      queue:
        name: default  # Squash - one commit per tag update

  - name: Auto-merge GitHub Actions updates
    conditions:
      - author~=^renovate
      - label=dependencies
      - label=github-actions
    actions:
      queue:
        name: default  # Squash - clean single commit

  - name: Auto-merge Nix flake updates
    conditions:
      - author~=^renovate
      - label=dependencies
      - label=nix-flake
    actions:
      queue:
        name: default  # Squash - clean single commit
