pull_request_rules:
  - name: Auto-merge Renovate Docker updates
    conditions:
      - author=app/renovate
      - label=dependencies
      - label=docker
    actions:
      merge:
        method: rebase