priority_rules:
  - name: Renovate tag updates
    priority: 3000
    conditions:
      - author~=^renovate
      - label=tag-update
  - name: Renovate digest updates
    priority: 2500
    conditions:
      - author~=^renovate
      - label=digest-update
  - name: OCI workflow updates
    priority: 2000
    conditions:
      - label=update
      - label=digests
  - name: GitHub Actions updates
    priority: 1000
    conditions:
      - author~=^renovate
      - label=github-actions
  - name: Nix flake updates
    priority: 500
    conditions:
      - author~=^renovate
      - label=nix-flake

queue_rules:
  - name: default
    merge_method: rebase
  
  - name: squash-queue
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})
      {% if body %}

      {{ body }}
      {% endif %}

pull_request_rules:
  - name: Auto-merge OCI workflow updates
    conditions:
      - label=update
      - label=digests
      - "#approved-reviews-by>=0"  # No approval required for automated updates
    actions:
      queue:
        name: default  # Rebase - keep multiple commits for transparency
      delete_head_branch:
        force: true  # Delete the branch after merge

  - name: Auto-merge Renovate digest updates
    conditions:
      - author~=^renovate
      - label=dependencies
      - label=docker
      - label=digest-update
    actions:
      queue:
        name: default  # Rebase - preserve individual commits
      delete_head_branch:  # Delete the branch after merge

  - name: Auto-merge Renovate tag updates
    conditions:
      - author~=^renovate
      - label=dependencies
      - label=docker
      - label=tag-update
    actions:
      queue:
        name: default  # Rebase - preserve individual commits
      delete_head_branch:  # Delete the branch after merge

  - name: Auto-merge GitHub Actions updates
    conditions:
      - author~=^renovate
      - label=dependencies
      - label=github-actions
    actions:
      queue:
        name: default  # Rebase - preserve individual commits
      delete_head_branch:  # Delete the branch after merge

  - name: Auto-merge Nix flake updates
    conditions:
      - author~=^renovate
      - label=dependencies
      - label=nix-flake
    actions:
      queue:
        name: default  # Rebase - preserve individual commits
      delete_head_branch:  # Delete the branch after merge
